<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>john</string>
   </array>
  <key>name</key>
  <string>john</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.john</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.line.john</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(@\w+)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.john</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.bracket.john</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.bracket.john</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(@\w+)</string>
          <key>name</key>
          <string>entity.name.function.john</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.john</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.john</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.john</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.john</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\^?-?[0-9]+(?:\.[0-9]+)?\.\.\^?-?[0-9]+(?:\.[0-9]+)?(\.\.\^?-?[0-9]+(?:\.[0-9]+)?)?)</string>
          <key>name</key>
          <string>constant.numeric.john</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\*\d+)|(\+\d+))</string>
          <key>name</key>
          <string>constant.numeric.john</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(v)([0-9]+(?:\.[0-9]+){0,3}-(?:\w+)?)</string>
          <key>name</key>
          <string>constant.numeric.john</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(true|false|abyss|#)</string>
          <key>name</key>
          <string>keyword.john</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?(\.\d+)?(Z|\+\d{2}:\d{2})?)|(?:\d{4}-\d{2}-\d{2})|(?:\d{2}:\d{2}(:\d{2})?(\.\d+)?(Z|\+\d{2}:\d{2})?))</string>
          <key>name</key>
          <string>constant.numeric.john</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(P(\d+Y)?(\d+M)?(\d+W)?(\d+D)?(T(\d+H)?(\d+M)?(\d+S)?)?)</string>
          <key>name</key>
          <string>constant.numeric.john</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\d+.{1,2}[b\x{007c}B]\b)</string>
          <key>name</key>
          <string>constant.numeric.john</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(((-?(\d+e-\d+|\d*\.\d+(e-?[0-9]+)?|\d+)f?)|(0x([0-9a-fA-F]{8}){1,2}[rR])|(-?[0-9_]+(e[0-9]+)?)|(-?0x[0-9a-fA-F]+)|(-?0b[01]+)|(-?0o[01234567]+))\b)</string>
          <key>name</key>
          <string>constant.numeric.john</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([_a-zA-Z]\w*)</string>
          <key>name</key>
          <string>entity.other.attribute-name.john</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.delimeter.john</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\]\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.delimeter.john</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.delimeter.john</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\}\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.delimeter.john</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.delimeter.john</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__6</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.delimeter.john</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.delimeter.john</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__7</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.delimeter.john</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.delimeter.john</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__8</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.delimeter.john</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{002c}\x{003b}\x{003a}\x{003d}\s])</string>
          <key>name</key>
          <string>punctuation.delimeter.john</string>
        </dict>
       </array>
    </dict>
    <key>args</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([\x{002c}\s])</string>
          <key>name</key>
          <string>punctuation.delimeter.john</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\w\.]+)</string>
          <key>name</key>
          <string>string.john</string>
        </dict>
       </array>
    </dict>
    <key>escapes</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\\.)</string>
          <key>name</key>
          <string>constant.character.escape.john</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{0022}\x{0027}\x{005c}]+)</string>
          <key>name</key>
          <string>string.john</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#args</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#escapes</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#escapes</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__6</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__7</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__8</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
